// Generated by yi version 0.0.2
(function(){
  var defaultTimer;
  
  defaultTimer = setInterval(function(){
     showAlert("It's been like an hour! Get up and do some walk!");
  },3600000);
  var msg = document.getElementById("alert");

  function showAlert(message){
    alert(message);
  }

  function testAlert(){
    clearInterval(defaultTimer);
    var frequence = document.getElementById("frequency").value.trim(); 
    var message = document.getElementById('message').value.trim();
    console.log("F: " + frequence + " M: " +message);
    if(!frequence){
      frequence = 3600;
      console.log("Frequence is empty. Using Default.");
    }
      
    if (frequence !== parseInt(frequence).toString()) {
      msg.setAttribute("style", "display: inline-block");
      console.log("frequence is not a number");
    }else{
      frequence = parseInt(frequence);
      console.log("frequence is a number");
      msg.setAttribute("style", "display: none");
      frequence = frequence * 1000;
      console.log("Clear timer.");
      defaultTimer = setInterval(function(){
        showAlert(message);
      },frequence);
      console.log("New timer.")
    }  
  }



  document.getElementById("clickOK").addEventListener("click", testAlert);
  console.log("Initialized.");

})();